[workspace]
members = [
  "./types",
  "./api",
  "./api_unofficial",
  "./solution",
  "./workspace",
  "./cli",
]
resolver = "2"

[workspace.dependencies]
rustix = { version = "0.38.37", features = ["fs"] }

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
