[workspace]
members = [
  "./types",
  "./api",
  "./api_unofficial",
  "./solution",
  "./workspace",
  "./cli",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
